sudo: required

services:
  - docker

before_install:
  - sudo apt -qq update -y
  - sudo apt -qq install --only-upgrade docker-ce -y
  - docker info
  - cp -rv .docker $HOME/

script:
  - bash build-push.sh
