sudo: required

services:
  - docker

before_install:
  - cat $HOME/.docker/config.json
  - sudo apt -qq update -y
  - sudo apt -qq install --only-upgrade docker-ce -y
  - docker info

script:
  - bash build-push.sh
